export const words = [
  {
    id: "numbers",
    title: "Numbers",
    wordsMap: new Map([
      ["Бир", ["One"]],
      ["Эки", ["Two"]],
      ["Үч", ["Three"]],
      ["Төрт", ["Four"]],
      ["Беш", ["Five"]],
      ["Алты", ["Six"]],
      ["Жети", ["Seven"]],
      ["Сегиз", ["Eight"]],
      ["Тогуз", ["Nine"]],
      ["Он", ["Ten"]],
      ["Жүз", ["Hundred"]],
      ["Миң", ["Thousand"]],
      ["Он миң", ["Ten Thousand"]],
    ]),
  },
  {
    id: "directions",
    title: "Directions",
    wordsMap: new Map([
      ["Түндүк", ["North"]],
      ["Чыгыш", ["East"]],
      ["Батыш", ["West"]],
      ["Түштүк", ["South"]],
      ["Сол", ["Left"]],
      ["Оң", ["Right"]],
      ["Жогоруда", ["Above"]],
      ["Төмөндө", ["Below"]],
      ["Ичинде", ["Inside"]],
      ["Артта", ["Behind"]],
    ]),
  },
  {
    id: "adjectives",
    title: "Adjectives",
    wordsMap: new Map([
      ["Эски", ["Old"]],
      ["Бийик", ["High"]],
      ["Арзан", ["Cheap"]],
      ["Чоң", ["Big"]],
      ["Кичинекей", ["Small"]],
      ["Көптөр", ["Many"]],
      ["Жаңы", ["New"]],
      ["Аз", ["Few"]],
      ["Узун", ["Long"]],
      ["Кыска", ["Short"]],
    ]),
  },
  {
    id: "verbs",
    title: "Verbs",
    wordsMap: new Map([
      ["Баруу", ["Go"]],
      ["Көрүү", ["See"]],
      ["Айтуу", ["Say"]],
      ["Ичүү", ["Drink"]],
      ["Жолугушуу", ["Meet"]],
      ["Үйрөнүү", ["Study", "Learn"]],
      ["Эс алуу", ["Rest"]],
      ["Сатып алуу", ["Buy"]],
      ["Угуу", ["Listen"]],
      ["Келүү", ["Come"]],
      ["Сүйлөшүү", ["Talk"]],
      ["Чыгуу", ["Leave"]],
      ["Окуу", ["Read"]],
      ["Жазуу", ["Write"]],
    ]),
  },
  {
    id: "time",
    title: "Time",
    wordsMap: new Map([
      ["Күн", ["Day"]],
      ["Ай", ["Month"]],
      ["Түшкө маал", ["Noon"]],
      ["Жарымы", ["Half"]],
      ["Бөлүгү", ["Part"]],
      ["Убакыт", ["Time"]],
      ["Аралык", ["Interval"]],
      ["Жума", ["Week"]],
      ["Жыл", ["Year"]],
      ["Азыр", ["Now"]],
      ["Мурун", ["Before"]],
      ["Ар бири", ["Each"]],
    ]),
  },
  {
    id: "bodyParts",
    title: "Body Parts",
    wordsMap: new Map([
      ["Көз", ["Eye"]],
      ["Ооз", ["Mouth"]],
      ["Кулак", ["Ear"]],
      ["Кол", ["Hand"]],
      ["Бут", ["Foot"]],
    ]),
  },
];
