export { Home } from "./Home";
export { FullPost } from "./FullPost";
export { AddPost } from "./AddPost";
export { Registration } from "./Registration";
export { Login } from "./Login";
export { ProfileCard } from "./Profile";
export { WordsPage } from "./Words";
export { WordPage } from "./Word";
export { PageNotFound } from "./PageNotFound";
